### ISSUE TITLE
GCR Compare with RoG

### ISSUE THREAD

**Issue by Barcavin** [RManLuo/graph-constrained-reasoning#1]
Hi,

Both RoG and GCR are inspiring works on KGQA tasks. Furthermore, it is very interesting to see how the trie structure built from KG can be used to constrain the output of LLM for reasoning paths.

I am trying to find the subtle differences between RoG and GCR since they are mostly following the same pipeline. In my understanding, GCR has one more component, which is graph constrained decoding, compared to RoG during planning. Is this the only major difference? I wonder if I missed any other significant part that boosts GCR performance over RoG.

Thanks

**Comment by RManLuo** [comment]
Hi,

Thank you for your interest in our work. GCR builds on our previous project, RoG. Unlike RoG’s planning-retrieval framework, GCR uses graph-constrained decoding to directly generate KG-grounded reasoning paths, integrating the KG reasoning process seamlessly into the LLM decoding.

Best.
