### ISSUE TITLE
The difference between ROG and GCR

### ISSUE THREAD

**Issue by DecemberM** [RManLuo/graph-constrained-reasoning#2]
ROG is to process the knowledge graph into text data and then search, GCR is to search directly on the knowledge graph without any preprocessing, right？
Hoping to your reply

**Comment by RManLuo** [comment]
Thanks for your interest. The major difference is that, in GCR, we do not need the retrieval process used in RoG. GCR can directly consider the KG structure during reasoning.

**Comment by DecemberM** [comment]
http://datacon-14123.xyz/index.php/2024/11/22/datacon2024竞赛哋它亢seo赛题思路/
