### ISSUE TITLE
how to build dataset like RoG-webqsp RoG-cwq

### ISSUE THREAD

**Issue by DecemberM** [RManLuo/graph-constrained-reasoning#3]
Thanks for your answer. I hope to know how to build dataset like RoG-webqsp && RoG-cwq,is it possible to build dataset like  RoG-webqsp && RoG-cwq form private KG
I'll be grateful if you could reply

**Comment by DecemberM** [comment]
http://datacon-14123.xyz/index.php/2024/11/22/datacon2024竞赛哋它亢seo赛题思路/

**Comment by whq-27** [comment]
你好，我也有同样的需求，想使用自己所构建的知识图谱，链接已无法打开
